# Generated by Django 4.2.1 on 2023-05-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='name')),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=100)),
                ('gaurdian_name', models.CharField(max_length=100)),
                ('total_marks', models.IntegerField(max_length=100, null=True)),
            ],
        ),
    ]
