# Generated by Django 4.2.1 on 2023-05-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='age',
            field=models.IntegerField(verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='total_marks',
            field=models.IntegerField(null=True, verbose_name='mark'),
        ),
        migrations.AlterModelTable(
            name='studentmodel',
            table='student table',
        ),
    ]
